spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}:3306/planner
    username: ${DATABASE_LOGIN}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.mariadb.jdbc.Driver
    continueOnError: true
    initialization-mode: never
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      write_dates_as_timestamps: false
server:
  port: ${SERVER_PORT}
  ssl:
    enabled: ${SECURITY_ENABLED}
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
